# -*- coding: utf-8 -*-
"""BSIM4999_OCR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t1L2dHgqzkl05ocyUecbb-vOqZoTbA3T
"""

# ============================================================
# ENHANCED OCR PROCESSOR - SKIPS VIDEOS
# ============================================================
# This script processes a CSV file containing Twitter/X posts
# and performs OCR ONLY on images (skips videos)
# ============================================================

# Install required libraries (run once in Google Colab)
!pip install pandas pillow pytesseract
!apt-get install tesseract-ocr tesseract-ocr-eng tesseract-ocr-chi-sim tesseract-ocr-jpn -y

# Import required libraries
import pandas as pd
import requests
import time
import os
import json
import re
from datetime import datetime
from google.colab import files
import pytesseract
from PIL import Image
from io import BytesIO
import warnings
warnings.filterwarnings('ignore')

# ============================================================
# CONFIGURATION
# ============================================================
class OCRConfig:
    """Configuration settings for OCR processing"""

    # Image download settings
    DOWNLOAD_TIMEOUT = 15  # seconds
    MAX_RETRIES = 3
    USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'

    # OCR settings
    MAX_IMAGES_PER_POST = 5  # Process up to 5 images per post
    OCR_LANGUAGE = 'eng'  # Default language (eng, chi_sim, jpn, etc.)
    OCR_CONFIG = '--psm 6 -l eng'  # PSM 6 = assume uniform text block

    # Processing settings
    DELAY_BETWEEN_IMAGES = 0.5  # seconds
    DELAY_BETWEEN_POSTS = 1.0   # seconds

    # Image preprocessing
    MAX_IMAGE_SIZE = (2000, 2000)  # Resize large images for better performance

    # Video detection patterns
    VIDEO_PATTERNS = [
        'video',
        'mp4',
        'mov',
        'avi',
        'youtube',
        'youtu.be',
        't.co/video',
        'twitter.com.*/video',
        'watch?v=',
        'vimeo',
        'instagram.com/p/',
        'tiktok',
        'twitch'
    ]

# ============================================================
# VIDEO DETECTION FUNCTION
# ============================================================
def is_video_url(url):
    """
    Detect if a URL points to video content
    Returns: True if video, False otherwise
    """
    if not url:
        return False

    url_lower = url.lower()

    # Check for video file extensions
    video_extensions = ['.mp4', '.mov', '.avi', '.mkv', '.webm', '.flv', '.wmv']
    if any(url_lower.endswith(ext) for ext in video_extensions):
        return True

    # Check for video platform patterns
    video_patterns = [
        'youtube.com/watch',
        'youtu.be/',
        'vimeo.com/',
        'tiktok.com/',
        'instagram.com/reel',
        'instagram.com/tv',
        'twitch.tv',
        'twitter.com/i/videos',
        '/video/',
        'videos/',
        'watch?v='
    ]

    if any(pattern in url_lower for pattern in video_patterns):
        return True

    # Check if URL contains video in path
    if '/video' in url_lower or '/videos' in url_lower:
        return True

    # Check for Twitter video patterns
    if 'pbs.twimg.com' in url_lower and 'video' in url_lower:
        return True

    # Check media key patterns - Twitter videos often have 'video' in media_key
    if 'video' in url_lower:
        # But be careful: sometimes 'video' appears in image URLs from Twitter
        # Only flag if it's explicitly a video URL
        if 'video' in url_lower and not ('jpg' in url_lower or 'jpeg' in url_lower or 'png' in url_lower):
            return True

    return False

def identify_media_type(media_url):
    """
    Identify if media URL is image or video
    Returns: 'image', 'video', or 'unknown'
    """
    if not media_url:
        return 'unknown'

    # Check for video patterns
    if is_video_url(media_url):
        return 'video'

    # Check for image patterns
    image_extensions = ['.jpg', '.jpeg', '.png', '.gif', '.webp', '.bmp']
    url_lower = media_url.lower()

    if any(url_lower.endswith(ext) for ext in image_extensions):
        return 'image'

    # Twitter CDN images typically have pbs.twimg.com/media/
    if 'pbs.twimg.com/media/' in url_lower and not 'video' in url_lower:
        return 'image'

    # If it's from Twitter CDN and not clearly video, assume it's an image
    if 'pbs.twimg.com' in url_lower:
        return 'image'

    return 'unknown'

# ============================================================
# IMAGE DOWNLOADER
# ============================================================
def download_image(image_url, max_retries=OCRConfig.MAX_RETRIES):
    """
    Download image from URL with retry logic
    Returns: PIL Image object or None if download fails
    """
    for attempt in range(max_retries):
        try:
            headers = {'User-Agent': OCRConfig.USER_AGENT}
            response = requests.get(image_url,
                                  headers=headers,
                                  timeout=OCRConfig.DOWNLOAD_TIMEOUT)
            response.raise_for_status()

            # Check content type
            content_type = response.headers.get('Content-Type', '').lower()
            if 'video' in content_type:
                print(f"      🎬 Skipping video content")
                return None

            # Open image from bytes
            img = Image.open(BytesIO(response.content))
            return img

        except requests.exceptions.Timeout:
            print(f"    ⏱ Timeout downloading {image_url[:50]}... (attempt {attempt + 1}/{max_retries})")
            time.sleep(2)
        except requests.exceptions.RequestException as e:
            print(f"    📡 Download error: {str(e)[:50]} (attempt {attempt + 1}/{max_retries})")
            time.sleep(2)
        except Exception as e:
            print(f"    ❌ Image processing error: {str(e)[:50]}")
            return None

    return None

# ============================================================
# IMAGE PREPROCESSOR
# ============================================================
def preprocess_image(img):
    """
    Preprocess image for better OCR accuracy
    """
    try:
        # Convert to RGB if necessary
        if img.mode not in ('L', 'RGB'):
            img = img.convert('RGB')

        # Resize large images for better OCR performance
        if img.size[0] > OCRConfig.MAX_IMAGE_SIZE[0] or img.size[1] > OCRConfig.MAX_IMAGE_SIZE[1]:
            img.thumbnail(OCRConfig.MAX_IMAGE_SIZE, Image.Resampling.LANCZOS)

        return img

    except Exception as e:
        print(f"      ⚠ Preprocessing error: {str(e)}")
        return img

# ============================================================
# OCR TEXT EXTRACTOR
# ============================================================
def extract_text_from_image(img):
    """
    Extract text from image using Tesseract OCR
    Returns: extracted text string
    """
    try:
        # Preprocess image
        img = preprocess_image(img)

        # Perform OCR
        extracted_text = pytesseract.image_to_string(img, config=OCRConfig.OCR_CONFIG)

        # Clean up extracted text
        extracted_text = extracted_text.strip()
        extracted_text = ' '.join(extracted_text.split())  # Normalize whitespace
        extracted_text = extracted_text.replace('\n', ' ').replace('\r', ' ')

        return extracted_text

    except Exception as e:
        print(f"      🔍 OCR error: {str(e)}")
        return ""

# ============================================================
# MAIN OCR PROCESSING FUNCTION (WITH VIDEO SKIPPING)
# ============================================================
def process_media_with_ocr(media_urls, post_id="", verbose=True):
    """
    Process media URLs - skip videos, perform OCR only on images
    Args:
        media_urls: list of media URLs
        post_id: optional post identifier for logging
        verbose: print progress messages
    Returns:
        tuple: (combined_ocr_text, successful_images_count, skipped_videos_count)
    """
    if not media_urls:
        return "", 0, 0

    ocr_texts = []
    successful_count = 0
    skipped_videos = 0

    # Limit number of media items processed
    urls_to_process = media_urls[:OCRConfig.MAX_IMAGES_PER_POST]

    if verbose and len(media_urls) > OCRConfig.MAX_IMAGES_PER_POST:
        print(f"    ℹ Limiting to first {OCRConfig.MAX_IMAGES_PER_POST} of {len(media_urls)} media items")

    for i, url in enumerate(urls_to_process, 1):
        if verbose:
            print(f"    📷 Media {i}/{len(urls_to_process)}")

        # Identify media type
        media_type = identify_media_type(url)

        if media_type == 'video':
            if verbose:
                print(f"      🎬 Skipping video content")
            skipped_videos += 1
            continue

        elif media_type == 'image':
            if verbose:
                print(f"      🖼 Processing image...")

            # Download image
            img = download_image(url)

            if img:
                # Extract text
                extracted = extract_text_from_image(img)

                if extracted:
                    ocr_texts.append(extracted)
                    successful_count += 1
                    if verbose:
                        print(f"      ✓ Extracted {len(extracted)} characters: {extracted[:80]}...")
                else:
                    if verbose:
                        print(f"      ⚠ No text found in image")
            else:
                if verbose:
                    print(f"      ❌ Failed to download image")

        else:
            if verbose:
                print(f"      ❓ Unknown media type, skipping")
            continue

        # Delay between images
        time.sleep(OCRConfig.DELAY_BETWEEN_IMAGES)

    # Combine all OCR results
    if ocr_texts:
        combined = " | ".join(ocr_texts)
        return combined, successful_count, skipped_videos
    else:
        return "", 0, skipped_videos

# ============================================================
# ENHANCED CSV PROCESSOR (WITH VIDEO DETECTION)
# ============================================================
def process_csv_with_ocr_enhanced(input_file,
                                   media_url_column='media_urls',
                                   text_column='original_text',
                                   output_file='output_with_ocr.csv',
                                   delimiter='|',
                                   verbose=True):
    """
    Process CSV file and perform OCR ONLY on images (skip videos)
    """

    print("="*70)
    print("🚀 ENHANCED OCR PROCESSING (SKIPPING VIDEOS)")
    print("="*70)

    # Read CSV file
    print(f"\n📂 Reading CSV file: {input_file}")
    try:
        df = pd.read_csv(input_file)
        print(f"✓ Loaded {len(df)} rows")
        print(f"  Columns: {list(df.columns)}")
    except Exception as e:
        print(f"❌ Error reading CSV: {str(e)}")
        return None

    # Check required columns
    if media_url_column not in df.columns:
        print(f"\n❌ Error: '{media_url_column}' column not found in CSV")
        print(f"  Available columns: {list(df.columns)}")
        return None

    # Check Tesseract installation
    try:
        tesseract_version = pytesseract.get_tesseract_version()
        print(f"\n✅ Tesseract OCR version: {tesseract_version}")
    except Exception as e:
        print(f"\n❌ Tesseract OCR not properly installed: {str(e)}")
        return None

    # Create new columns for OCR results
    df['ocr_text'] = ''
    df['ocr_success'] = ''
    df['images_processed'] = 0
    df['videos_skipped'] = 0
    df['media_types'] = ''
    df['combined_text'] = ''

    # Process each row
    successful_posts = 0
    total_images_processed = 0
    total_videos_skipped = 0
    posts_with_videos = 0

    print("\n" + "="*70)
    print("📸 PROCESSING MEDIA WITH OCR (SKIPPING VIDEOS)")
    print("="*70)

    for idx, row in df.iterrows():
        print(f"\n📝 Row {idx + 1}/{len(df)}")

        # Get media URLs
        media_cell = str(row[media_url_column]) if pd.notna(row[media_url_column]) else ""

        if media_cell and media_cell != 'nan':
            # Split URLs by delimiter
            media_urls = [url.strip() for url in media_cell.split(delimiter) if url.strip()]

            # Identify media types
            media_types = []
            images = []
            videos = []

            for url in media_urls:
                media_type = identify_media_type(url)
                media_types.append(media_type)
                if media_type == 'image':
                    images.append(url)
                elif media_type == 'video':
                    videos.append(url)

            # Store media types
            df.at[idx, 'media_types'] = ' | '.join(media_types)
            df.at[idx, 'videos_skipped'] = len(videos)

            if videos:
                posts_with_videos += 1
                print(f"  🎬 Found {len(videos)} video(s) - skipping OCR")

            if images:
                print(f"  🖼 Found {len(images)} image(s) - processing OCR")

                # Show post preview
                original_text = row[text_column] if text_column in df.columns else ""
                if original_text and len(str(original_text)) > 50:
                    print(f"  📝 Original text: {str(original_text)[:50]}...")
                elif original_text:
                    print(f"  📝 Original text: {str(original_text)}")

                # Process only images
                ocr_result, success_count, skipped = process_media_with_ocr(
                    images,
                    post_id=idx,
                    verbose=verbose
                )

                # Update DataFrame
                if ocr_result:
                    df.at[idx, 'ocr_text'] = ocr_result
                    df.at[idx, 'ocr_success'] = 'Yes'
                    successful_posts += 1
                    total_images_processed += success_count

                    # Combine original text with OCR text
                    if text_column in df.columns and pd.notna(row[text_column]):
                        original_text = str(row[text_column])
                        combined = f"{original_text} [OCR: {ocr_result}]"
                        df.at[idx, 'combined_text'] = combined
                    else:
                        df.at[idx, 'combined_text'] = ocr_result
                else:
                    df.at[idx, 'ocr_success'] = 'No text found' if success_count == 0 else 'No'
                    if text_column in df.columns:
                        df.at[idx, 'combined_text'] = str(row[text_column])

                df.at[idx, 'images_processed'] = success_count
                total_videos_skipped += skipped

            else:
                print(f"  ℹ No images found (only videos or unknown media)")
                df.at[idx, 'ocr_success'] = 'Only videos'
                if text_column in df.columns:
                    df.at[idx, 'combined_text'] = str(row[text_column])
        else:
            print(f"  ℹ No media in this post")
            df.at[idx, 'ocr_success'] = 'No media'
            if text_column in df.columns:
                df.at[idx, 'combined_text'] = str(row[text_column])

        # Delay between posts
        time.sleep(OCRConfig.DELAY_BETWEEN_POSTS)

    # Print summary
    print("\n" + "="*70)
    print("📊 OCR PROCESSING COMPLETE")
    print("="*70)
    print(f"Total posts processed: {len(df)}")
    print(f"Posts with images: {len(df[df['images_processed'] > 0])}")
    print(f"Posts with videos: {posts_with_videos}")
    print(f"Posts with successful OCR: {successful_posts}")
    print(f"Total images processed: {total_images_processed}")
    print(f"Total videos skipped: {total_videos_skipped}")
    print(f"OCR success rate: {(successful_posts / len(df[df['images_processed'] > 0]) * 100 if len(df[df['images_processed'] > 0]) > 0 else 0):.1f}%")

    # Save results
    print(f"\n💾 Saving results to: {output_file}")
    df.to_csv(output_file, index=False, encoding='utf-8-sig')
    print(f"✓ File saved successfully")

    return df

# ============================================================
# QUICK START FUNCTION
# ============================================================
def quick_process_enhanced(csv_file, media_col='media_urls', text_col='original_text'):
    """
    Quick function to process a CSV file (skipping videos)
    """
    return process_csv_with_ocr_enhanced(
        input_file=csv_file,
        media_url_column=media_col,
        text_column=text_col,
        output_file=csv_file.replace('.csv', '_with_ocr_enhanced.csv'),
        verbose=True
    )

# ============================================================
# ANALYZE MEDIA TYPES FUNCTION
# ============================================================
def analyze_media_types(csv_file, media_col='media_urls', delimiter='|'):
    """
    Analyze media types in the CSV file before processing
    """
    print("="*70)
    print("🔍 MEDIA TYPE ANALYSIS")
    print("="*70)

    # Read CSV
    df = pd.read_csv(csv_file)

    total_images = 0
    total_videos = 0
    total_unknown = 0
    posts_with_images = 0
    posts_with_videos = 0
    posts_with_mixed = 0

    for idx, row in df.iterrows():
        media_cell = str(row[media_col]) if pd.notna(row[media_col]) else ""

        if media_cell and media_cell != 'nan':
            media_urls = [url.strip() for url in media_cell.split(delimiter) if url.strip()]

            has_image = False
            has_video = False

            for url in media_urls:
                media_type = identify_media_type(url)
                if media_type == 'image':
                    total_images += 1
                    has_image = True
                elif media_type == 'video':
                    total_videos += 1
                    has_video = True
                else:
                    total_unknown += 1

            if has_image and has_video:
                posts_with_mixed += 1
            elif has_image:
                posts_with_images += 1
            elif has_video:
                posts_with_videos += 1

    print(f"\n📊 Media Statistics:")
    print(f"  • Total media items: {total_images + total_videos + total_unknown}")
    print(f"    - Images: {total_images} ({total_images/(total_images+total_videos+total_unknown)*100:.1f}%)")
    print(f"    - Videos: {total_videos} ({total_videos/(total_images+total_videos+total_unknown)*100:.1f}%)")
    print(f"    - Unknown: {total_unknown}")

    print(f"\n📸 Posts by media type:")
    print(f"  • Posts with only images: {posts_with_images}")
    print(f"  • Posts with only videos: {posts_with_videos}")
    print(f"  • Posts with mixed (images + videos): {posts_with_mixed}")
    print(f"  • Total posts with images: {posts_with_images + posts_with_mixed}")
    print(f"  • Total posts with videos: {posts_with_videos + posts_with_mixed}")

    return {
        'total_images': total_images,
        'total_videos': total_videos,
        'posts_with_images': posts_with_images + posts_with_mixed,
        'posts_with_videos': posts_with_videos + posts_with_mixed
    }

# ============================================================
# MAIN EXECUTION
# ============================================================
if __name__ == "__main__":
    print("="*70)
    print("🔍 ENHANCED TWITTER/X POST OCR PROCESSOR")
    print("📹 SKIPS VIDEOS - ONLY PROCESSES IMAGES")
    print("="*70)

    # Ask user for CSV file
    print("\nPlease upload your CSV file (should contain 'media_urls' column)")

    uploaded = files.upload()

    if uploaded:
        filename = list(uploaded.keys())[0]
        print(f"\n✓ File uploaded: {filename}")

        # First, analyze media types
        print("\n" + "="*70)
        print("📊 ANALYZING MEDIA TYPES...")
        print("="*70)
        analyze_media_types(filename)

        # Ask if user wants to proceed
        proceed = input("\n\nDo you want to proceed with OCR processing? (y/n): ")

        if proceed.lower() == 'y':
            # Process the file
            output_file = filename.replace('.csv', '_with_ocr_enhanced.csv')
            result_df = process_csv_with_ocr_enhanced(
                input_file=filename,
                media_url_column='media_urls',
                text_column='original_text',
                output_file=output_file,
                verbose=True
            )

            if result_df is not None:
                # Show sample results
                print("\n" + "="*70)
                print("📋 SAMPLE RESULTS")
                print("="*70)

                # Show posts that had OCR text from images
                ocr_posts = result_df[result_df['ocr_text'] != '']
                if len(ocr_posts) > 0:
                    print("\n📸 Posts with extracted text from images:")
                    for idx, row in ocr_posts.head(3).iterrows():
                        print(f"\nRow {idx + 1}:")
                        print(f"  Date: {row.get('date', 'N/A')} {row.get('time', 'N/A')}")
                        print(f"  Images processed: {row.get('images_processed', 0)}")
                        print(f"  Videos skipped: {row.get('videos_skipped', 0)}")
                        print(f"  OCR Text: {row['ocr_text'][:100]}...")

                # Show posts with videos that were skipped
                video_posts = result_df[result_df['videos_skipped'] > 0]
                if len(video_posts) > 0:
                    print(f"\n🎬 Posts with videos (skipped): {len(video_posts)}")
                    for idx, row in video_posts.head(2).iterrows():
                        print(f"\n  Date: {row.get('date', 'N/A')} {row.get('time', 'N/A')}")
                        print(f"  Videos skipped: {row.get('videos_skipped', 0)}")
                        print(f"  Media types: {row.get('media_types', 'N/A')}")

                # Download result
                print(f"\n📥 Downloading result file: {output_file}")
                files.download(output_file)
        else:
            print("\n✗ OCR processing cancelled")
    else:
        print("No file uploaded")

# ============================================================
# DOWNLOAD OCR PROCESSED CSV FILE
# ============================================================

from google.colab import files
import pandas as pd
import os

# File name from your OCR processing
filename = "2025-2026_donald_trump_posts_with_ocr.csv"

# ============================================================
# METHOD 1: Direct Download
# ============================================================
print("="*70)
print("📥 DOWNLOADING OCR PROCESSED FILE")
print("="*70)

# Check if file exists
if os.path.exists(filename):
    # Get file size
    file_size = os.path.getsize(filename) / (1024 * 1024)  # Size in MB

    print(f"\n✓ File found: {filename}")
    print(f"  File size: {file_size:.2f} MB")

    # Download the file
    files.download(filename)
    print(f"\n✓ Download initiated for {filename}")
else:
    print(f"\n❌ File not found: {filename}")
    print("Available CSV files in current directory:")
    for file in os.listdir():
        if file.endswith('.csv'):
            print(f"  - {file}")
